version: '3.8'

services:
  
  siem-server:
    build:
      context: ./siem-log-server
    ports:
      - "5000:5000"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB_NAME=alertix_db
      - SERVER_PORT=5000
      - FLASK_SECRET_KEY=yoursecretproductionkeyhere
    depends_on:
      - elasticsearch
      - mongodb
    volumes:
      - ./siem-log-server/logs:/app/logs

  
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data

  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - elasticsearch

volumes:
  mongo_data:
  es_data: